### PR TITLE
Copyright and misc POM changes

### PR DESCRIPTION
**Pull request by yaminikb**
-Copyright text corrections in all files
-Removed unwanted directories
-Fixed bugs in POM

### CODE REVIEW

**Comment by nigeldeakin** [comment]
I'm not sure you should be changing the source code, as it represents a released version of JMS.

**Review by bshannon — APPROVED** [review]
It looks like the bulk of the changes here are to update the license header to the newer version.  Those changes are not necessary, but also not harmful.  In some cases it looks like the entire file was changed, perhaps that's due to changes in line terminators?

I'm fine with removing all the unneeded files.

**Comment by yaminikb** [comment]
@bshannon All changes happened via the copyright plugin which seems to be fixing line terminators as well.

**Comment by yaminikb** [comment]
@bshannon requesting review again

**Review by bshannon — APPROVED** [review]
Looks good!

**Pull request merged**
